alter table VKR_PRODUCT_IN_THE_SHOP add constraint FK_VKR_PRODUCT_IN_THE_SHOP_ON_PRODUCT foreign key (PRODUCT_ID) references VKR_PRODUCT(ID);
alter table VKR_PRODUCT_IN_THE_SHOP add constraint FK_VKR_PRODUCT_IN_THE_SHOP_ON_SHOP foreign key (SHOP_ID) references VKR_SHOP(ID);
create index IDX_VKR_PRODUCT_IN_THE_SHOP_ON_PRODUCT on VKR_PRODUCT_IN_THE_SHOP (PRODUCT_ID);
create index IDX_VKR_PRODUCT_IN_THE_SHOP_ON_SHOP on VKR_PRODUCT_IN_THE_SHOP (SHOP_ID);
