alter table VKR_PURCHASED_PRODUCT add constraint FK_VKR_PURCHASED_PRODUCT_ON_SHOP foreign key (SHOP_ID) references VKR_SHOP(ID);
create index IDX_VKR_PURCHASED_PRODUCT_ON_SHOP on VKR_PURCHASED_PRODUCT (SHOP_ID);
