-- begin VKR_PURCHASE
alter table VKR_PURCHASE add constraint FK_VKR_PURCHASE_ON_CUSTOMER foreign key (CUSTOMER_ID) references SEC_USER(ID)^
create index IDX_VKR_PURCHASE_ON_CUSTOMER on VKR_PURCHASE (CUSTOMER_ID)^
-- end VKR_PURCHASE
-- begin VKR_PURCHASED_PRODUCT
alter table VKR_PURCHASED_PRODUCT add constraint FK_VKR_PURCHASED_PRODUCT_ON_PRODUCT_IN_THE_SHOP foreign key (PRODUCT_IN_THE_SHOP_ID) references VKR_PRODUCT_IN_THE_SHOP(ID)^
alter table VKR_PURCHASED_PRODUCT add constraint FK_VKR_PURCHASED_PRODUCT_ON_PURCHASE foreign key (PURCHASE_ID) references VKR_PURCHASE(ID)^
create index IDX_VKR_PURCHASED_PRODUCT_ON_PRODUCT_IN_THE_SHOP on VKR_PURCHASED_PRODUCT (PRODUCT_IN_THE_SHOP_ID)^
create index IDX_VKR_PURCHASED_PRODUCT_ON_PURCHASE on VKR_PURCHASED_PRODUCT (PURCHASE_ID)^
-- end VKR_PURCHASED_PRODUCT
-- begin VKR_NETWORK
alter table VKR_NETWORK add constraint FK_VKR_NETWORK_ON_NETWORK_CEO foreign key (NETWORK_CEO_ID) references SEC_USER(ID)^
create index IDX_VKR_NETWORK_ON_NETWORK_CEO on VKR_NETWORK (NETWORK_CEO_ID)^
-- end VKR_NETWORK
-- begin VKR_PRODUCT
alter table VKR_PRODUCT add constraint FK_VKR_PRODUCT_ON_CATEGORY foreign key (CATEGORY_ID) references VKR_PRODUCT_CATEGORY(ID)^
alter table VKR_PRODUCT add constraint FK_VKR_PRODUCT_ON_COMPANY foreign key (COMPANY_ID) references VKR_COMPANY(ID)^
create index IDX_VKR_PRODUCT_ON_CATEGORY on VKR_PRODUCT (CATEGORY_ID)^
create index IDX_VKR_PRODUCT_ON_COMPANY on VKR_PRODUCT (COMPANY_ID)^
-- end VKR_PRODUCT
-- begin VKR_PRODUCT_IN_THE_SHOP
alter table VKR_PRODUCT_IN_THE_SHOP add constraint FK_VKR_PRODUCT_IN_THE_SHOP_ON_PRODUCT foreign key (PRODUCT_ID) references VKR_PRODUCT(ID)^
alter table VKR_PRODUCT_IN_THE_SHOP add constraint FK_VKR_PRODUCT_IN_THE_SHOP_ON_SHOP foreign key (SHOP_ID) references VKR_SHOP(ID)^
create index IDX_VKR_PRODUCT_IN_THE_SHOP_ON_PRODUCT on VKR_PRODUCT_IN_THE_SHOP (PRODUCT_ID)^
create index IDX_VKR_PRODUCT_IN_THE_SHOP_ON_SHOP on VKR_PRODUCT_IN_THE_SHOP (SHOP_ID)^
-- end VKR_PRODUCT_IN_THE_SHOP
-- begin VKR_PRODUCT_CATEGORY
create unique index IDX_VKR_PRODUCT_CATEGORY_UK_NAME on VKR_PRODUCT_CATEGORY (NAME) where DELETE_TS is null ^
-- end VKR_PRODUCT_CATEGORY
-- begin VKR_SHOP
alter table VKR_SHOP add constraint FK_VKR_SHOP_ON_ADDRESS foreign key (ADDRESS_ID) references VKR_ADDRESS(ID)^
alter table VKR_SHOP add constraint FK_VKR_SHOP_ON_NETWORK foreign key (NETWORK_ID) references VKR_NETWORK(ID)^
alter table VKR_SHOP add constraint FK_VKR_SHOP_ON_MANAGER foreign key (MANAGER_ID) references SEC_USER(ID)^
create index IDX_VKR_SHOP_ON_ADDRESS on VKR_SHOP (ADDRESS_ID)^
create index IDX_VKR_SHOP_ON_NETWORK on VKR_SHOP (NETWORK_ID)^
create index IDX_VKR_SHOP_ON_MANAGER on VKR_SHOP (MANAGER_ID)^
-- end VKR_SHOP
-- begin VKR_COMPANY
alter table VKR_COMPANY add constraint FK_VKR_COMPANY_ON_COMPANY_CEO foreign key (COMPANY_CEO_ID) references SEC_USER(ID)^
create index IDX_VKR_COMPANY_ON_COMPANY_CEO on VKR_COMPANY (COMPANY_CEO_ID)^
-- end VKR_COMPANY
